name: PyBuilder Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python and Node.js
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          node-version: '20'
           
      - name: Install PyBuilder
        run: | 
          python -m pip install --upgrade pip
          pip install pybuilder
     
      - name: Build and Test
        run: pyb

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/reports  

      - name: List Files  # Optional steps
        run: |
          ls -R
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-web-app
          path: src
        
  sonarqube_analysis:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  

  deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub using PAT
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        working-directory: src/main/python
        run: |
          docker build -t pros2018/mywebapp:latest .
          docker push pros2018/mywebapp:latest
